package media.toloka.rfa.radio.model.enumerate;

public enum EServerState {

    STATION_CREATE("STATION_CREATE"),
    STATION_ALLOCATE("STATION_ALLOCATE"),
    STATION_SETNGINXCONFIG("STATION_SETNGINXCONFIG"),
    STATION_INITIALMIGRATE("STATION_INITIALMIGRATE"),
    STATION_MIGRATEVERSION("STATION_MIGRATEVERSION"),
    STATION_STOP("STATION_STOP"),
    STATION_START("STATION_START"),
    STATION_RUN("STATION_RUN"),
    STATION_CHECKSTATUS("STATION_CHECKSTATUS"),
    STATION_PAY("STATION_PAY"),
    STATION_BLOKED("STATION_BLOKED"),
    STATION_UNBLOKED("STATION_UNBLOKED"),
    STATION_LOCKED("STATION_LOCKED"),
    STATION_UNLOCKED("STATION_UNLOCKED"),
    STATION_DELETE("STATION_DELETE");

    public final String label;

    private EServerState(String label) {
        this.label = label;
    }
}
