create database ${LIBRETIME_POSTGRESQL_DBNAME};
create user ${LIBRETIME_POSTGRESQL_USERNAME} with encrypted password '${LIBRETIME_POSTGRESQL_PASSWORD}';
grant all privileges on database ${LIBRETIME_POSTGRESQL_DBNAME} to ${LIBRETIME_POSTGRESQL_USERNAME};
ALTER DATABASE ${LIBRETIME_POSTGRESQL_DBNAME} OWNER TO ${LIBRETIME_POSTGRESQL_USERNAME};
