package media.toloka.rfa.rpc.model;

public enum ERPCJobType {
    // CONTRACT
    JOB_CONTRACT_CREATE("JOB_CONTRACT_CREATE"),
    JOB_CONTRACT_STOP("JOB_CONTRACT_STOP"),
    JOB_CONTRACT_PAUSE("JOB_CONTRACT_PAUSE"),
    JOB_CONTRACT_RESUME("JOB_CONTRACT_RESUME"),
    JOB_CONTRACT_ADD_STATION("JOB_CONTRACT_ADD_STATION"),
    JOB_CONTRACT_ADD_NAME("JOB_CONTRACT_ADD_NAME"),
    JOB_CONTRACT_MOVE_STATION("JOB_CONTRACT_MOVE_STATION"),
    // STATION
    JOB_STATION_CREATE("JOB_STATION_CREATE"),
    JOB_STATION_ALLOCATE("JOB_STATION_ALLOCATE"),
    JOB_STATION_LIBRETIME_MIGRATE("JOB_STATION_LIBRETIME_MIGRATE"),
    JOB_STATION_LIBRETIME_MIGRATE_VERSION("JOB_STATION_LIBRETIME_MIGRATE_VERSION"),
    JOB_STATION_PREPARE_NGINX("JOB_STATION_PREPARE_NGINX"),
    JOB_STATION_START("JOB_STATION_START"),
    JOB_STATION_STOP("JOB_STATION_STOP"),
    JOB_STATION_DELETE("JOB_STATION_DELETE"),
    JOB_STATION_PAUSE("JOB_STATION_PAUSE"),
    JOB_STATION_GET_STATISTIC("JOB_STATION_GET_STATISTIC"),
    JOB_STATION_GET_STATUS("JOB_STATION_GET_STATUS"),
    JOB_STATION_ENABLE("JOB_STATION_ENABLE"),
    JOB_STATION_DISABLE("JOB_STATION_DISABLE");

    public final String label;

    private ERPCJobType(String label) {
        this.label = label;
    }
}
