package media.toloka.rfa.rpc.model;

public enum ERPCJobType {
    JOB_CONTRACT_CREATE("JOB_CONTRACT_CREATE"),
    JOB_CONTRACT_STOP("JOB_CONTRACT_STOP"),
    JOB_CONTRACT_PAUSE("JOB_CONTRACT_PAUSE"),
    JOB_CONTRACT_RESUME("JOB_CONTRACT_RESUME"),
    JOB_CONTRACT_ADD_STATION("JOB_CONTRACT_ADD_STATION"),
    JOB_CONTRACT_ADD_NAME("JOB_CONTRACT_ADD_NAME"),
    JOB_CONTRACT_MOVE_STATION("JOB_CONTRACT_MOVE_STATION"),
    JOB_RADIO_CREATE("JOB_RADIO_CREATE"),
    JOB_RADIO_START("JOB_RADIO_START"),
    JOB_RADIO_STOP("JOB_RADIO_STOP"),
    JOB_RADIO_DELETE("JOB_RADIO_DELETE"),
    JOB_RADIO_PAUSE("JOB_RADIO_PAUSE"),
    JOB_RADIO_GET_STATISTIC("JOB_RADIO_GET_STATISTIC"),
    JOB_RADIO_ENABLE("JOB_RADIO_ENABLE"),
    JOB_RADIO_DISABLE("JOB_RADIO_DISABLE");

    public final String label;

    private ERPCJobType(String label) {
        this.label = label;
    }
}
